name: ci-ubuntu.yml
on:
  push:
    branches:
      - main
jobs:
  build_docker_and_test:
    runs-on: ubuntu-latest
    name: Run docker compose yml
    container: docker
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Builds the docker composed image"
        id: build
        run: docker compose build
      - name: "Brings up the docker compose and runs the tests"
        id: run-test
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: docker compose up --abort-on-container-exit --exit-code-from integrationtest
      - name: "Setup SSH"
        id: setup-ssh
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - name: "Copy files to VPS"
        id: copy-files
        run: |
          rsync -avz -e "ssh -p ${{ secrets.VPS_IP_PORT }} -o StrictHostKeyChecking=no" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/ProjectCC/logservice/

      - name: "Run Docker Compose on VPS"
        id: run-docker-compose
        run: |
          ssh -p ${{ secrets.VPS_IP_PORT }} -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} \
          "cd /ProjectCC/logservice && docker compose up -d"  
        



