name: ci-ubuntu.yml
on:
  push:
    branches:
      - main
jobs:
  build_docker_and_test:
    runs-on: windows-latest
    name: Run docker compose yml
    container: docker
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Builds the docker composed image"
        id: build
        run: docker compose build
      - name: "Brings up the docker compose and runs the tests"
        id: run-test
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: docker compose up --abort-on-container-exit --exit-code-from client
          for i in {1..10}; do
            if curl -s http://localhost:8080/healthcheck | grep "healthy"; then
              echo "Application is healthy."
              exit 0
            else
              echo "Waiting for application to be healthy..."
              sleep 10
            fi
          done
